apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegram-bot
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegram-bot
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 15s

